// ----------------------------------------------------------------------
// <copyright file="SolutionBuilderTest.cs" company="Xavier Solau">
// Copyright © 2021-2026 Xavier Solau.
// Licensed under the MIT license.
// See LICENSE file in the project root for full license information.
// </copyright>
// ----------------------------------------------------------------------

using Shouldly;
using SoloX.CodeQuality.Test.Helpers.Solution;
using Xunit;

namespace SoloX.CodeQuality.Test.Helpers.UTest.Solution
{
    public class SolutionBuilderTest
    {
        [Theory]
        [InlineData("SoloX.CodeQuality.TestNuget")]
        [InlineData("SoloX.CodeQuality.PreReleaseTestNuget")]
        public void IsShouldBuildASolutionWithATestProject(string packageName)
        {
            var configurationName = DirectoryHelper.ProbConfiguration<SolutionBuilderTest>();

            var root = new RandomGenerator().RandomString(4);

            // Let's create a solution in the random root folder.
            var solution = new SolutionBuilder(root, "TestSolution")
                // Set up the nuget.config to use a dedicated nuget cache and to specify where to get the nuget
                // packages we want to test (generated in the same solution).
                .WithNugetConfig(@"PkgCache", configuration =>
                {
                    // We want to use the package generated by the projects SoloX.CodeQuality.WebHost and SoloX.CodeQuality.Playwright.
                    configuration
                        .UsePackageSources(src =>
                        {
                            src.Clear()
                                .Add($"../../../../../{packageName}/bin/{configurationName}")
                                .AddNugetOrg();
                        });
                })
                // Set up a xunit project to use the nugets.
                .WithProject("TestProject", "xunit", configuration =>
                {
                    configuration.UsePackageReference(packageName);
                })
                // Finally create the solution.
                .Build();

            try
            {
                var actBuild = () => solution.Build();

                Should.NotThrow(actBuild);

                var actTest = () => solution.Test();

                Should.NotThrow(actTest);
            }
            finally
            {
                Directory.Delete(root, true);
            }
        }

        [Theory]
        [InlineData("Debug", "net8.0")]
        [InlineData("Debug", "net9.0")]
        [InlineData("Debug", "net10.0")]
        [InlineData("Release", "net8.0")]
        [InlineData("Release", "net9.0")]
        [InlineData("Release", "net10.0")]
        public void IsShouldBuildASolutionWithTargetFrameworkAndConfiguration(string configuration, string framework)
        {
            var configurationName = DirectoryHelper.ProbConfiguration<SolutionBuilderTest>();

            var root = new RandomGenerator().RandomString(4);

            var projectName = "TestProject";

            // Let's create a solution in the random root folder.
            var solution = new SolutionBuilder(root, "TestSolution")
                // Set up a xunit project to use the nugets.
                .WithProject(projectName, "xunit", framework, configuration =>
                {
                })
                // Finally create the solution.
                .Build(configuration);

            try
            {
                var actBuild = () => solution.Build();

                Should.NotThrow(actBuild);

                var path = solution.GetProjectBinaryPath(projectName);

                var assemblyFile = Path.Combine(path, framework, $"{projectName}.dll");

                File.Exists(assemblyFile).ShouldBeTrue();
            }
            finally
            {
                Directory.Delete(root, true);
            }
        }

        [Theory]
        [InlineData("SoloX.CodeQuality.TestTool", "testtool")]
        [InlineData("SoloX.CodeQuality.PreReleaseTestTool", "prereleasetesttool")]
        public void IsShouldBuildASolutionUsingADotnetTool(string toolProject, string toolName)
        {
            var configurationName = DirectoryHelper.ProbConfiguration<SolutionBuilderTest>();

            var root = new RandomGenerator().RandomString(4);

            // Let's create a solution in the random root folder.
            var solution = new SolutionBuilder(root, "TestSolution")
                // Set up the nuget.config to use a dedicated nuget cache and to specify where to get the nuget
                // packages we want to test (generated in the same solution).
                .WithNugetConfig(@"PkgCache", configuration =>
                {
                    // We want to use the package generated by the projects SoloX.CodeQuality.WebHost and SoloX.CodeQuality.Playwright.
                    configuration
                        .UsePackageSources(src =>
                        {
                            src.Clear()
                                .Add(@$"../../../../../{toolProject}/bin/{configurationName}")
                                .AddNugetOrg();
                        });
                })
                .WithDotnetTools(configuration =>
                {
                    configuration
                        .UseTool(toolProject);
                })
                // Finally create the solution.
                .Build();

            try
            {
                var actBuild = () => solution.Build();

                Should.NotThrow(actBuild);

                var actTest = () => solution.RunTool(toolName, $"a1 a2 --debug:false");

                var logs = Should.NotThrow(actTest).LogMessages;

                logs.ShouldNotBeEmpty();

                logs[0].Message.ShouldBe("Hello, World!");
                logs[1].Message.ShouldBe("given arg 0: a1");
                logs[2].Message.ShouldBe("given arg 1: a2");
            }
            finally
            {
                Directory.Delete(root, true);
            }
        }

        [Fact]
        public void IsShouldBuildASolutionWithARootEditorConfigFile()
        {
            var configurationName = DirectoryHelper.ProbConfiguration<SolutionBuilderTest>();

            var root = new RandomGenerator().RandomString(4);

            // Let's create a solution in the random root folder.
            var solution = new SolutionBuilder(root, "TestSolution")
                // We want to have the editorconfig at the root of the solution to be sure that the build process won't be
                // looking for any parent editorconfig outside of the current test solution context.
                .WithRootEditorConfig()
                // Finally create the solution.
                .Build();

            try
            {
                File.Exists(Path.Combine(root, "TestSolution", ".editorconfig")).ShouldBeTrue();
            }
            finally
            {
                Directory.Delete(root, true);
            }
        }
    }
}
