// ----------------------------------------------------------------------
// <copyright file="CodeQualityPackageTest.cs" company="Xavier Solau">
// Copyright © 2021-2026 Xavier Solau.
// Licensed under the MIT license.
// See LICENSE file in the project root for full license information.
// </copyright>
// ----------------------------------------------------------------------

using Shouldly;
using SoloX.CodeQuality.Test.Helpers;
using SoloX.CodeQuality.Test.Helpers.Snapshot;
using SoloX.CodeQuality.Test.Helpers.Solution;
using SoloX.CodeQuality.Test.Helpers.Solution.Exceptions;

namespace SoloX.CodeQuality.E2ETest.Package
{
    public class CodeQualityPackageTest
    {
        [Theory]
        [InlineData("SoloX.CodeQuality.Test", false)]
        [InlineData("SoloX.CodeQuality.Prod", true)]
        public async Task IsShouldDeployNugetPackageAndBuildWithWarningOrError(string codeQualityNugetName, bool withError)
        {
            var configurationName = DirectoryHelper.ProbConfiguration<CodeQualityPackageTest>();

            var root = new RandomGenerator().RandomString(4);

            var absoluteCodeQualityNugetLocation = Path.GetFullPath(
                Path.Combine(DirectoryHelper.ThisFilePathLocation(),
                    "..", "..", "..", "libs", codeQualityNugetName, "bin",
                    configurationName));

            // Let's create a solution in the random root folder.
            var solution = new SolutionBuilder(root, "TestSolution")
                // We want to have the editorconfig at the root of the solution to be sure that the build process won't be
                // looking for any parent editorconfig outside of the current test solution context.
                .WithRootEditorConfig()
                // Set up the nuget.config to use a dedicated nuget cache and to specify where to get the nuget
                // packages we want to test (generated in the same solution).
                .WithNugetConfig(@"PkgCache", configuration =>
                {
                    // We want to use the package generated by the projects SoloX.CodeQuality.WebHost and SoloX.CodeQuality.Playwright.
                    configuration
                        .UsePackageSources(src =>
                        {
                            src.Clear()
                                .Add(absoluteCodeQualityNugetLocation)
                                .AddNugetOrg();
                        });
                })
                // Set up a xunit project to use the nugets.
                .WithProject("TestProject", "xunit", "net10.0", configuration =>
                {
                    configuration
                        // Configure the package reference on the package to test. In this case SoloX.CodeQuality.Playwright.
                        .UsePackageReference(codeQualityNugetName)
                        .UsePackageReference("Shouldly")
                        .UsePackageReference("NSubstitute")
                        // Register Properties to be used in the project file.
                        .UseProperties(props =>
                        {
                            props
                                .Add(("CodeQualityHeaderCompanyName", "Xavier Solau"),
                                    ("CodeQualityHeaderCopyright", "Copyright © 2021-2026 Xavier Solau"),
                                    ("CodeQualityHeaderLicense", "MIT"),
                                    ("CodeQualityHeaderLicenseFile", "LICENSE"));
                        })
                        // Create the files
                        .UseFiles(files =>
                        {
                            files
                                .Remove("UnitTest1.cs")
                                .Add(
                                    @"../CA2012RuleTest.cs",
                                    "CA2012RuleTest.cs",
                                    [("SoloX.CodeQuality.E2ETest", "TestProject")]);
                        });
                })
                // Finally create the solution.
                .Build();

            try
            {
                // Let's clean the project from the generated files to be sure that the build will be able to
                // generate them again.
                Directory.Delete(Path.Combine(root, "TestSolution", "TestProject", "obj"), true);
                File.Delete(Path.Combine(root, "TestSolution", "TestProject", ".editorconfig"));
                File.Delete(Path.Combine(root, "TestSolution", "TestProject", "TestProject.xml"));

                // Let's build the solution and be sure that it works.
                var actBuild = () => solution.Build();

                if (withError)
                {
                    var exception = Should.Throw<SolutionBuilderException<SolutionError>>(actBuild);

                    exception.ProcessResult!.GetLogs().ShouldContain("error CA2012");
                }
                else
                {
                    var buildResult = Should.NotThrow(actBuild);

                    buildResult.ExitCode.ShouldBe(0);

                    buildResult.GetLogs().ShouldContain("warning CA2012");
                }
            }
            finally
            {
                Directory.Delete(root, true);
            }
        }

        [Theory]
        [InlineData("SoloX.CodeQuality.Test", "utf-8-bom")]
        [InlineData("SoloX.CodeQuality.Prod", "utf-8-bom")]
        [InlineData("SoloX.CodeQuality.Test", "utf-8")]
        [InlineData("SoloX.CodeQuality.Prod", "utf-8")]
        public async Task IsShouldDeployNugetPackageAndGenerateEditorConfig(string codeQualityNugetName, string charset)
        {
            var configurationName = DirectoryHelper.ProbConfiguration<CodeQualityPackageTest>();

            var root = new RandomGenerator().RandomString(4);

            var absoluteCodeQualityNugetLocation = Path.GetFullPath(
                Path.Combine(DirectoryHelper.ThisFilePathLocation(),
                    "..", "..", "..", "libs", codeQualityNugetName, "bin",
                    configurationName));

            // Let's create a solution in the random root folder.
            var solution = new SolutionBuilder(root, "TestSolution")
                // We want to have the editorconfig at the root of the solution to be sure that the build process won't be
                // looking for any parent editorconfig outside of the current test solution context.
                .WithRootEditorConfig()
                // Set up the nuget.config to use a dedicated nuget cache and to specify where to get the nuget
                // packages we want to test (generated in the same solution).
                .WithNugetConfig(@"PkgCache", configuration =>
                {
                    // We want to use the package generated by the projects SoloX.CodeQuality.WebHost and SoloX.CodeQuality.Playwright.
                    configuration
                        .UsePackageSources(src =>
                        {
                            src.Clear()
                                .Add(absoluteCodeQualityNugetLocation)
                                .AddNugetOrg();
                        });
                })
                // Set up a xunit project to use the nugets.
                .WithProject("TestProject", "xunit", "net10.0", configuration =>
                {
                    configuration
                        // Configure the package reference on the package to test. In this case SoloX.CodeQuality.Playwright.
                        .UsePackageReference(codeQualityNugetName)
                        // Register Properties to be used in the project file.
                        .UseProperties(props =>
                        {
                            props
                                .Add(("CodeQualityCharset", charset));
                        });
                })
                // Finally create the solution.
                .Build();

            try
            {
                var actBuild = () => solution.Build();

                Should.Throw<SolutionBuilderException<SolutionError>>(actBuild);

                var editorConfigText = await File.ReadAllTextAsync(
                    Path.Combine(root, "TestSolution", "TestProject", ".editorconfig"),
                    CancellationToken.None);

                if (!editorConfigText.Contains("end_of_line = crlf", StringComparison.InvariantCulture))
                {
                    // Since the snapshot are generated with crlf, we need to replace the end_of_line value in the editorconfig
                    // text to be sure that the snapshot comparison will work.
                    editorConfigText = editorConfigText
                        .Replace("end_of_line = cr", "end_of_line = crlf", StringComparison.InvariantCulture)
                        .Replace("end_of_line = lf", "end_of_line = crlf", StringComparison.InvariantCulture);
                }

                var sh = SnapshotTestBuilder
                    .Create()
                    .WithThisFilePathLocation()
                    .WithTextStrategy()
                    .Build();

                await sh.CompareSnapshotAsync(
                    nameof(IsShouldDeployNugetPackageAndGenerateEditorConfig) + codeQualityNugetName + charset,
                    editorConfigText);
            }
            finally
            {
                Directory.Delete(root, true);
            }
        }
    }
}
