// ----------------------------------------------------------------------
// <copyright file="CodeQualityPackageTest.cs" company="Xavier Solau">
// Copyright © 2021-2026 Xavier Solau.
// Licensed under the MIT license.
// See LICENSE file in the project root for full license information.
// </copyright>
// ----------------------------------------------------------------------

using Shouldly;
using SoloX.CodeQuality.Test.Helpers;
using SoloX.CodeQuality.Test.Helpers.Solution;

namespace SoloX.CodeQuality.E2ETest.Package
{
    public class CodeQualityPackageTest
    {
        [Fact]
        public async Task IsShouldDeployNugetPackageAndBuildWithWarning()
        {
            var configurationName = DirectoryHelper.ProbConfiguration<CodeQualityPackageTest>();

            var root = new RandomGenerator().RandomString(4);

            var absoluteCodeQualityTestNugetLocation = Path.GetFullPath(
                Path.Combine(DirectoryHelper.ThisFilePathLocation(),
                    "..", "..", "..", "libs", "SoloX.CodeQuality.Test", "bin",
                    configurationName));

            // Let's create a solution in the random root folder.
            var solution = new SolutionBuilder(root, "TestSolution")
                // We want to have the editorconfig at the root of the solution to be sure that the build process won't be
                // looking for any parent editorconfig outside of the current test solution context.
                .WithRootEditorConfig()
                // Set up the nuget.config to use a dedicated nuget cache and to specify where to get the nuget
                // packages we want to test (generated in the same solution).
                .WithNugetConfig(@"PkgCache", configuration =>
                {
                    // We want to use the package generated by the projects SoloX.CodeQuality.WebHost and SoloX.CodeQuality.Playwright.
                    configuration
                        .UsePackageSources(src =>
                        {
                            src.Clear()
                                .Add(absoluteCodeQualityTestNugetLocation)
                                .AddNugetOrg();
                        });
                })
                // Set up a xunit project to use the nugets.
                .WithProject("TestProject", "xunit", "net10.0", configuration =>
                {
                    configuration
                        // Configure the package reference on the package to test. In this case SoloX.CodeQuality.Playwright.
                        .UsePackageReference("SoloX.CodeQuality.Test")
                        .UsePackageReference("Shouldly")
                        .UsePackageReference("NSubstitute")
                        // Register Properties to be used in the project file.
                        .UseProperties(props =>
                        {
                            props
                                .Add(("CodeQualityHeaderCompanyName", "Xavier Solau"),
                                    ("CodeQualityHeaderCopyright", "Copyright © 2021-2026 Xavier Solau"),
                                    ("CodeQualityHeaderLicense", "MIT"),
                                    ("CodeQualityHeaderLicenseFile", "LICENSE"));
                        })
                        // Create the files
                        .UseFiles(files =>
                        {
                            files
                                .Remove("UnitTest1.cs")
                                .Add(
                                    @"../CA2012RuleTest.cs",
                                    "CA2012RuleTest.cs",
                                    [("SoloX.CodeQuality.E2ETest", "TestProject")]);
                        });
                })
                // Finally create the solution.
                .Build();

            try
            {
                // Let's clean the project from the generated files to be sure that the build will be able to
                // generate them again.
                Directory.Delete(Path.Combine(root, "TestSolution", "TestProject", "obj"), true);
                File.Delete(Path.Combine(root, "TestSolution", "TestProject", ".editorconfig"));
                File.Delete(Path.Combine(root, "TestSolution", "TestProject", "TestProject.xml"));

                // Let's build the solution and be sure that it works.
                var actBuild = () => solution.Build();

                var buildResult = Should.NotThrow(actBuild);

                buildResult.ExitCode.ShouldBe(0);
            }
            finally
            {
                Directory.Delete(root, true);
            }
        }
    }
}
